R/package.R
This allows a loop to continue after error and to return the error itself. Fixes #12.
``` r
library(gh)
foo <- function(endpoints) {
lapply(endpoints, function(x) try(gh(x)))
}
res <- foo(c("/emojis", "/licenses", "/gitignore/templates"))
str(res, max.level = 1)
#> List of 3
#>  $ :List of 888
#>   .. [list output truncated]
#>   ..- attr(*, "method")= chr "GET"
#>   ..- attr(*, "response")=List of 26
#>   .. ..- attr(*, "class")= chr [1:2] "insensitive" "list"
#>   ..- attr(*, "class")= chr "gh_response"
#>  $ :Class 'try-error'  atomic [1:1] Error in gh(x) : GitHub API error 415 Unsupported Media Type
#> 
#>   .. ..- attr(*, "condition")=List of 4
#>   .. .. ..- attr(*, "class")= chr [1:2] "condition" "error"
#>  $ :List of 120
#>   .. [list output truncated]
#>   ..- attr(*, "method")= …
```
=> Add call and error class to the cond when status code >= 300

R/package.R, R/pagination.R, man/gh.Rd
*the rebased version of PR #16*
New features of the API generally require a custom media type during the preview period. See for example the new [Licenses API](https://developer.github.com/v3/licenses/). The new `.send_headers` argument allows user to provide additional header fields or to override defaults.
I also changed the capitalization of `Accept` and `User-Agent`. I know header field names aren't *supposed* to be case sensitive and yet, when specifying custom media type, I have seen sometimes they are? The first error here is expected because the custom media type is incorrectly specified in the default headers. But the second error seems to come from specificying the `"accept"` field instead of "`Accept`". The third call demonstrates what this PR is adding. The fourth and fifth …
=> Add send headers

R/parse_end_point.R
Silences a warning that occurs whenever user supplies input that has length greater than one. This sort of input is ultimately destined to become a query parameter and not substituted into the endpoint URL. I don't think this needs to be documented (?).
Example: the `labels` one can provide when opening an issue.
``` r
library(gh)
retval <- gh("POST /repos/:owner/:repo/issues",
owner = "STAT545-UBC", repo = "test-repo",
title = "hw04 peer review", body = "review your peer's work",
assignee = "jennybc", labels = c("peer-review", "hw04"))
#> Warning in gsub(paste0(":", n, "\\b"), p, endpoint): argument 'replacement'
#> has length > 1 and only the first element will be used
```
=> attempt endpoint parameter substitution with exactly 1 item

R/package.R, man/gh.Rd
Added support for Github Enteprises: allowing users to specify custom Github API url as discussed in #19
=> Added Github Enterprise support

R/package.R
I make a lot of bulk requests and get all sorts of errors. It's easier for me to troubleshoot if the error message is exposed. PR causes inclusion of the very informative "Please upgrade your plan to create a new private repository."
``` r
res <- gh("POST /user/repos", name = "borat", private = TRUE)
#> Error in gh("POST /user/repos", name = "borat", private = TRUE) :
#>   GitHub API error: 422 Unprocessable Entity
#>   Please upgrade your plan to create a new private repository.
```
=> reveal error message

R/package.R
as per this discussion https://github.com/gaborcsardi/gh/commit/d2f8a7cab5b746c5d4a4599bb4406fd1b272a2e0#commitcomment-15717354
It wasn't just the `gh_response` class that was being lost but all attributes. Is there some more compact way to do this?
=> retain attributes when .limit is enforced

R/gh_request.R, R/utils.R, tests/testthat/test-build_request.R
If all names are `""`, they need to be stripped, in order to produce the correct JSON body. Discovered when trying to set issue labels.
=> Strip non names

R/gh_response.R, tests/testthat/test-error.R
This allows you to catch a github_error or the exact status code
directly.
=> Add additional classes to returned error objects

tests/testthat/helper-offline.R
Re: #62 `skip_if_offline()` errors when cannot resolve host
=> Catch ping_port() error when cannot resolve host; fixes #62

tests/testthat/helper-offline.R
I started to use this skipping approach over in googledrive and we are giving it a thorough workout. We find that `skip_if_offline()` can happen sporadically for no genuine reason. I suspect it's better to determine online vs offline once, at setup, then use that state throughout.
=> Common offline status for all tests

R/git.R, R/utils.R
I'm getting failures in `usethis` because `git_remotes()` does not handle anonymous remotes with no URL fields. This kind of remotes are used by magit to store metadata. E.g. the second one in this example:
```r
#> $ remote "lionel-":List of 2
#>  ..$ url  : chr "https://github.com/lionel-/oldie.git"
#>  ..$ fetch: chr "+refs/heads/*:refs/remotes/lionel-/*"
#> $ remote          :List of 1
#>  ..$ pushDefault: chr "lionel-"
#> $ remote "r-lib"  :List of 2
#>  ..$ url  : chr "https://github.com/r-lib/oldie.git"
#>  ..$ fetch: chr "+refs/heads/*:refs/remotes/r-lib/*"
```
This patch remove objects with empty fields before plucking them. I didn't write an unit test because `git_remotes()` is not a pure function and depends on the git configuration.
=> Fix URL plucking with empty remotes

R/gh_response.R
Fixes #60 even more. Specifically https://github.com/r-lib/gh/issues/60#issuecomment-354770688
---
``` r
gh::gh("GET /repos/gapminder/gapminder")
#> Error in gh_process_response(raw): 
#> GitHub API error (404): 404 Not Found
#> Message: Not Found
#> Read more at https://developer.github.com/v3
#> 
#> URL not found: https://api.github.com/repos/gapminder/gapminder
```
Created on 2018-02-14 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
=> Print the URL that cannot be found for 404

R/gh_response.R, R/package.R, R/print.R, inst/NEWS.md, man/gh.Rd, tests/testthat/test-mock-repos.R
-  Check GH media type to determine response type
-  Set raw response class as c("gh_response", "raw")
-  Modify print method to be raw-friendly
-  Document the fact that response type changes
-  Add test, NEWS
This makes the function not strictly type-safe but I think returning a raw vector makes sense for a raw response.
Also, new tests are skipped, as the other repo tests are because they are not mocked, but they pass when run.
=> Raw GitHub responses returned as raw vectors

R/pagination.R, man/gh_next.Rd
Users looking into `gh_next()` probably want the `.limit` argument. Do we want to advertise even more prominently?
=> Point to .limit argument from gh_next()

R/package.R, man/gh.Rd
so that fewer requests are needed. Need to expose argument to avoid collisions with `per_page` given in `...` .
=> Increase per_page if .limit is given

README.Rmd, README.md
Fixes #90 
- Add instruction and example that shows that you can just copy and paste the API endpoints from the documentation.
- Add to [README.Rmd](https://github.com/r-lib/gh/blob/master/README.Rmd) the [`Environment Variables`](https://github.com/r-lib/gh#environment-variables) section. It was only on [README.md](https://github.com/r-lib/gh/blob/master/README.md) file.
=> Emphasise copy and paste from API

NEWS.md, R/package.R
This is a very simple fix for #114 to avoid calling `update_progress_bar()` when `.progress = FALSE`.
=> Fix error when .progress = FALSE in gh()

R/gh_token.R
This is a small change I made in #123 which should happen no matter what.
``` r
(val1 <- "a")
#> [1] "a"
(val2 <- 1)
#> [1] 1
tryCatch(
{
val1 <- "b"
stop("oh no")
}, error = function(e) {
val2 <- 2  
}
)
val1
#> [1] "b"
val2
#> [1] 1
(val1 <- "a")
#> [1] "a"
(val2 <- 1)
#> [1] 1
tryCatch(
{
val1 <- "b"
stop("oh no")
}, error = function(e) {
val2 <<- 2  
}
)
val1
#> [1] "b"
val2
#> [1] 2
```
<sup>Created on 2020-08-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
=> Assign in parent

R/gh.R
This is related to #135, I was also seeing strange behavior with the search API and I think I understand the cause now.
Most of the GitHub api endpoints either return a single result as a single json object (e.g. `GET /user`) or multiple results as a json array (e.g. `GET /orgs/:org/members`). However, there are a few endpoints where the endpoint returns a single json object that then contains the paginated array (e.g. `GET /repos/:owner/:repo/actions/runs` and `GET /search/repositories`) - the problem arises for these latter cases.
This pull request has a proposed fix to deal with the merging of these types separately so that we get the "right" behavior for all three cases. The bug is a bit insidious because any results past the first page are concatenated to the result object, but …
=> Pagination merge issue

R/gh.R
Use 'total_count' and info from the schema on
how to calculate the "length" of a response.
Fixes #135.
=> Fix pagination for various response types

tests/testthat/helper-offline.R, tests/testthat/test-mock-repos.R
=> Empty GH_TESTING no longer fails tests

DESCRIPTION, NEWS.md, R/gh_token.R, R/gh_whoami.R, inst/WORDLIST, man/gh_token.Rd, man/gh_whoami.Rd, tests/testthat/test-gh_token.R
fix #148 
update the regular expression to match the new token formats.
* Do we want to allow for the non-PAT prefixes? in other words, should only `ghp_` prefixes be allowed? (this PR allows the 5 prefixes mentioned in the [blog post](https://github.blog/changelog/2021-03-04-authentication-token-format-updates/)
* Should [tests](https://github.com/r-lib/gh/blob/master/tests/testthat/test-gh_token.R#L59-L63) be modified to account for this regular expression change?
* Do we want to already allow for up to 255 characters?
=> update PAT validation for new token formats

R/errors.R
I did this because it feels like `call.` does not have the usual effect. I figured this has since been fixed in the compat file. But even after I update, `call.` doesn't work the way I expect.
Is this expected behaviour? I'm talking about the `Error in FALSE` part.
``` r
gh:::gh_pat("aa")
#> Error in FALSE: GitHub PAT must have one of these forms:
#>   * 40 hexadecimal digits (older PATs)
#>   * A 'ghp_' prefix followed by 36 to 251 more characters (newer PATs)
```
<sup>Created on 2021-04-01 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0.9002)</sup>
Generated by https://github.com/r-lib/gh/blob/86eb3d975bef9133b62c82176c2d893ddb4110da/R/gh_token.R#L84-L89
=> Update with current errors.R from processx

R/gh_gql.R, man/gh_gql.Rd
Proposition of use for graphql query to retrieve the graphql rate limit, different from the REST API one as explained here: https://docs.github.com/en/graphql/overview/resource-limitations
_I will let you recreate the documentation as it needs {roxygenlabs} that I dont have._
=> New example of graphql query

NEWS.md, R/gh_request.R, tests/testthat/_snaps/gh_request.md, tests/testthat/test-gh_request.R, tests/testthat/test-mock-repos.R
=> Allow lower-case method

NEWS.md, R/gh_token.R, tests/testthat/test-gh_token.R
Add support for the new token format for [fine-grained PATs](https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/).
The new tokens start with "github_pat_" prefix, but are subject to change according to the announcement.
=> Add support for fine-grained PATs (#171)

NEWS.md, R/gh.R, R/gh_request.R, R/gh_response.R, R/pagination.R, R/print.R, man/gh.Rd, tests/testthat/_snaps/print.md, tests/testthat/test-gh_response.R, tests/testthat/test-pagination.R, tests/testthat/test-print.R
Testing this revealed that I failed to set up `max_wait` correctly; it got discarded by the final line of `gh_build_request()`. And even if I had caught that, it still wasn't recorded in the response object so pagination could preserve the value.
So now the request captures the complete request list made up by gh and reuses that when paginating. I'll probably refactor this in the future to reuse the same httr2 request.
=> Implement request_throttling

vignettes/managing-personal-access-tokens.Rmd
Document that PATs can now expire and the default expiration time is 30 days #160
=> Document that PATs can now expire w/ add default expiration

DESCRIPTION, NEWS.md, R/gh.R, R/utils.R, tests/testthat/test-gh.R, tests/testthat/test-utils.R
Closes #197. 
Original issue suggested replacing mockery with `testthat::with_mock`, however the usage of mockery was to test parameter handling (accepting via both ... and a .params arg) so naive replacement caused an infinitely recursive call to gh_build_request. 
Resolved by refactoring parameter handling into its own function, `.parse_params()`, which is easier to test conventionally
=> refactor gh::gh parameter handling to make testable without mocking

R/pagination.R, tests/testthat/test-pagination.R
This fixes the case where the GitHub replaces a space with `+`, which then gets re-encoded to `%2B`, causing the page to return no results.
=> Use link url with parsing + building url

NEWS.md, R/gh.R, R/gh_response.R, tests/testthat/test-print.R
This is really simple to implement but I think it probably needs some way to suppress and it might cause problems with `R CMD check`. Maybe an option?
Fixes #203
=> Use httr2 cache

R/gh.R
This makes gh fail a little faster in the case that GitHub is not available (e.g. you're on bad airplane wifi)
=> Reduce connection timeout to 5s

DESCRIPTION, NEWS.md, R/gh_token.R, tests/testthat/test-gh_token.R
This commit brings support for Posit Connect's ["viewer-based credentials" feature][0] to `gh`.
~~Similar to [the recent work in `odbc`][1], the way this is exposed to R users is to require them to pass a Shiny session argument to `gh_token()`, either directly or via `gh()` or `gh_gql()`.~~
Checks for viewer-based credentials are designed to fall back gracefully to existing authentication methods. This is intended to allow users to -- for example -- develop and test a Shiny app that uses GitHub credentials in desktop Positron/RStudio or Posit Workbench and deploy it with no code changes to Connect.
Most of the actual work is outsourced to a new shared package, [`connectcreds`][2].
Unit tests are included.
[0]: https://docs.posit.co/connect/user/oauth-integrations/
[1]: …
=> Add support for viewer-based credentials on Posit Connect
